FROM node:16

RUN apt-get update -qq && apt-get install -y build-essential nodejs

WORKDIR /usr/src
COPY backend ./backend
COPY .wilco ./.wilco

# Pre-install npm packages
WORKDIR /usr/src/backend
RUN yarn install

