apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.backend.serviceName }}
  name: {{ .Values.backend.serviceName }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.backend.serviceName }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.backend.serviceName }}
    spec:
      containers:
        - args:
            - sh
            - -c
            - yarn start
          env:
            - name: DATABASE_URL
              value: "{{ .Values.database.connectionProtocol }}{{ .Values.database.serviceName }}:{{ .Values.database.servicePort }}/{{ .Values.database.databaseName }}"
            - name: NODE_ENV
              value: development
            - name: PORT
              value: "{{ .Values.backend.containerPort }}"
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          name: {{ .Values.backend.serviceName }}
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
              name: http  
              protocol: TCP
          startupProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      restartPolicy: Always
